services:
  arlo-cam-api:
    image: bschrameck/arlo-cam-api:latest
    container_name: arlo-cam-api
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./arlo-cam-api/config.yaml:/opt/arlo-cam-api/config.yaml:ro
      - ./arlo-cam-api/arlo.db:/opt/arlo-cam-api/arlo.db

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
