#!/usr/bin/env python3
"""Generate private Arlo, MediaMTX, and Frigate configuration from inventory.

The inventory is deliberately ignored by Git. Keep camera addresses, serials,
credentials, and Home Assistant entry IDs out of the repository.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

CAMERA_ID = re.compile(r"^[a-z0-9_]+$")
DEPLOYMENT_VERSION = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][A-Za-z0-9.-]+)?$")


def quoted(value: str) -> str:
    """Return a JSON string, which is also safe YAML scalar syntax."""
    return json.dumps(value)


def read_inventory(path: Path) -> dict[str, Any]:
    """Read and validate the minimal private deployment inventory."""
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as err:
        raise SystemExit(f"Cannot read inventory {path}: {err}") from err

    if not isinstance(data, dict):
        raise SystemExit("Inventory must be a JSON object")
    required_sections = {"deployment", "home_assistant", "frigate", "cameras"}
    if not required_sections.issubset(data):
        raise SystemExit("Inventory requires deployment, home_assistant, frigate, and cameras")

    deployment = data["deployment"]
    home_assistant = data["home_assistant"]
    frigate = data["frigate"]
    cameras = data["cameras"]
    if not isinstance(deployment, dict) or not isinstance(home_assistant, dict) or not isinstance(frigate, dict):
        raise SystemExit("deployment, home_assistant, and frigate must be objects")
    if not isinstance(cameras, list) or not cameras:
        raise SystemExit("cameras must be a non-empty array")

    url = str(home_assistant.get("url", "")).rstrip("/")
    parsed = urlsplit(url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        raise SystemExit("home_assistant.url must be an absolute HTTP(S) URL")

    version = str(deployment.get("version", ""))
    if not DEPLOYMENT_VERSION.fullmatch(version):
        raise SystemExit("deployment.version must be a semantic version, for example 1.0.0")
    for image_key in ("arlo_cam_api_image", "mediamtx_image"):
        image = str(deployment.get(image_key, ""))
        if not image or image.endswith(":latest") or (":" not in image and "@sha256:" not in image):
            raise SystemExit(f"deployment.{image_key} must be pinned to a tag or digest, never latest")

    required_frigate = {
        "mqtt_host",
        "mqtt_user",
        "mqtt_password",
        "mqtt_topic_prefix",
        "mediamtx_host",
    }
    missing = sorted(required_frigate - frigate.keys())
    if missing:
        raise SystemExit(f"frigate is missing: {', '.join(missing)}")

    camera_ids: set[str] = set()
    serials: set[str] = set()
    for camera in cameras:
        if not isinstance(camera, dict):
            raise SystemExit("Each camera must be an object")
        camera_id = str(camera.get("id", ""))
        address = str(camera.get("address", "")).strip()
        serial = str(camera.get("serial", "")).strip()
        if not CAMERA_ID.fullmatch(camera_id):
            raise SystemExit("Camera id must use lowercase letters, numbers, and underscores")
        if not address or "/" in address or not serial:
            raise SystemExit("Each camera requires a host/IP address and serial")
        if camera_id in camera_ids or serial in serials:
            raise SystemExit("Camera ids and serials must be unique")
        camera_ids.add(camera_id)
        serials.add(serial)
    return data


def write(path: Path, content: str, version: str, *, header: bool = True) -> None:
    """Write one generated file, creating only its parent directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    prefix = f"# Deployment version {version}; generated by scripts/generate_deployment.py. Do not edit.\n" if header else ""
    path.write_text(prefix + content)


def generate(
    inventory: dict[str, Any], output: Path, entry_id: str, deployment_version: str | None
) -> None:
    """Render all service configuration files from a single inventory."""
    if not re.fullmatch(r"[A-Za-z0-9_-]+", entry_id):
        raise SystemExit("home-assistant-entry-id contains unsupported characters")
    if deployment_version is not None:
        if not DEPLOYMENT_VERSION.fullmatch(deployment_version):
            raise SystemExit("deployment-version must be a semantic version")
        inventory = {**inventory, "deployment": {**inventory["deployment"], "version": deployment_version}}
    home_assistant = inventory["home_assistant"]
    deployment = inventory["deployment"]
    frigate = inventory["frigate"]
    cameras = inventory["cameras"]
    webhook_root = f"{str(home_assistant['url']).rstrip('/')}/api/webhook/arlo_cam_api_{entry_id}"

    write(
        output / "arlo-cam-api/config.yaml",
        "\n".join(
            [
                'WifiCountryCode: "US"',
                "NotifyRegisteredAndStatusUpdate: true",
                "NotifyOnMotionAlert: true",
                "NotifyOnMotionTimeoutAlert: false",
                f"MotionRecordingWebHookUrl: {quoted(webhook_root + '_motion')}",
                f"StatusUpdateWebHookUrl: {quoted(webhook_root + '_status')}",
                'MotionTimeoutWebHookUrl: "http://127.0.0.1:9/disabled"',
                'RegistrationWebHookUrl: "http://127.0.0.1:9/disabled"',
                'ButtonPressWebHookUrl: "http://127.0.0.1:9/disabled"',
                "",
            ]
        ),
        str(deployment["version"]),
    )

    media_paths: list[str] = ["logLevel: info", "rtspAddress: :8554", "", "paths:"]
    for camera in cameras:
        media_paths.extend(
            [
                f"  {camera['id']}:",
                f"    source: rtsp://{camera['address']}/live",
                "    sourceOnDemand: yes",
                "    sourceOnDemandCloseAfter: 2s",
                "    rtspAnyPort: yes",
                "    maxReaders: 2",
            ]
        )
    write(output / "mediamtx/mediamtx.yml", "\n".join(media_paths) + "\n", str(deployment["version"]))

    frigate_config = [
        "mqtt:",
        f"  host: {quoted(str(frigate['mqtt_host']))}",
        f"  user: {quoted(str(frigate['mqtt_user']))}",
        f"  password: {quoted(str(frigate['mqtt_password']))}",
        f"  topic_prefix: {quoted(str(frigate['mqtt_topic_prefix']))}",
        "",
        "go2rtc:",
        "  streams:",
    ]
    for camera in cameras:
        camera_id = str(camera["id"])
        frigate_config.extend(
            [
                f"    {camera_id}:",
                f"      - rtsp://{frigate['mediamtx_host']}:8554/{camera_id}",
                f"      - ffmpeg:{camera_id}#audio=opus",
            ]
        )
    frigate_config.extend(["", "record:", "  enabled: true", "", "cameras:"])
    for camera in cameras:
        camera_id = str(camera["id"])
        frigate_config.extend(
            [
                f"  {camera_id}:",
                "    enabled: false",
                "    ffmpeg:",
                "      inputs:",
                f"        - path: rtsp://127.0.0.1:8554/{camera_id}",
                "          input_args: preset-rtsp-restream",
                "          roles: [detect, record, audio]",
                "    live:",
                "      streams:",
                f"        Main: {camera_id}",
            ]
        )
    write(output / "frigate/config.yml", "\n".join(frigate_config) + "\n", str(deployment["version"]))

    camera_map = {str(camera["serial"]): str(camera["id"]) for camera in cameras}
    write(
        output / "home-assistant/options.json",
        json.dumps(
            {
                "mqtt_prefix": frigate["mqtt_topic_prefix"],
                "camera_map": json.dumps(camera_map, sort_keys=True),
                "motion_tail_seconds": 15,
                "max_active_seconds": 180,
            },
            indent=2,
        )
        + "\n",
        str(deployment["version"]),
        header=False,
    )

    write(
        output / "docker-compose.yml",
        "\n".join(
            [
                "services:",
                "  arlo-cam-api:",
                f"    image: {quoted(str(deployment['arlo_cam_api_image']))}",
                "    container_name: arlo-cam-api",
                "    network_mode: host",
                "    restart: unless-stopped",
                "    volumes:",
                "      - ./arlo-cam-api/config.yaml:/opt/arlo-cam-api/config.yaml:ro",
                "      - ./arlo-cam-api/arlo.db:/opt/arlo-cam-api/arlo.db",
                "",
                "  mediamtx:",
                f"    image: {quoted(str(deployment['mediamtx_image']))}",
                "    container_name: mediamtx",
                "    network_mode: host",
                "    restart: unless-stopped",
                "    volumes:",
                "      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro",
                "",
            ]
        ),
        str(deployment["version"]),
    )

    generated_files = sorted(path for path in output.rglob("*") if path.is_file())
    manifest = {
        "deployment_version": deployment["version"],
        "images": {
            "arlo_cam_api": deployment["arlo_cam_api_image"],
            "mediamtx": deployment["mediamtx_image"],
        },
        "files": {
            str(path.relative_to(output)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in generated_files
        },
    }
    write(
        output / "deployment-manifest.json",
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        str(deployment["version"]),
        header=False,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--home-assistant-entry-id",
        required=True,
        help="Arlo Cam API config entry ID, required to build private webhook URLs",
    )
    parser.add_argument(
        "--deployment-version",
        help="Optional semantic deployment version; overrides inventory for this generated output",
    )
    args = parser.parse_args()
    generate(
        read_inventory(args.inventory),
        args.output,
        args.home_assistant_entry_id,
        args.deployment_version,
    )


if __name__ == "__main__":
    main()
